### PR TITLE
Updated camerax

### LINKED ISSUE #15: Crash when pressed take picture button
D/Camera2CameraImpl: mMeteringRepeating is ATTACHED, SessionConfig Surfaces: 2, CaptureConfig Surfaces: 1
D/UseCaseAttachState: Active and attached use case: [ImageCapture95977066] for camera: 1
D/UseCaseAttachState: All use case: [Preview101601115, ImageCapture95977066] for camera: 1
D/UseCaseAttachState: Active and attached use case: [ImageCapture95977066] for camera: 1
D/UseCaseAttachState: Active and attached use case: [Preview101601115, ImageCapture95977066] for camera: 1
D/UseCaseAttachState: Active and attached use case: [Preview101601115, ImageCapture95977066] for camera: 1
D/UseCaseAttachState: Active and attached use case: [Preview101601115, ImageCapture95977066] for camera: 1
E/InputEventReceiver: Exception dispatching input event.
E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
E/MessageQueue-JNI: java.lang.NoSuchMethodError: No virtual method takePicture(Ljava/io/File;Ljava/util/concurrent/Executor;Landroidx/camera/core/ImageCapture$OnImageSavedCallback;)V in class Landroidx/camera/view/CameraView; or its super classes (declaration of 'androidx.camera.view.CameraView' appears in /data/app/com.localise.app-25mD_WMiY_l9EwY8_Lc1OQ==/base.apk)
        at com.luck.picture.lib.instagram.InstagramCameraView$1.takePictures(InstagramCameraView.java:103)
        at com.luck.picture.lib.instagram.InstagramCaptureLayout.onTouchEvent(InstagramCaptureLayout.java:200)
        at android.view.View.dispatchTouchEvent(View.java:12527)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3026)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2705)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3054)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:444)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1835)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3465)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:402)
        at android.view.View.dispatchPointerEvent(View.java:12768)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5287)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5087)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4602)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4655)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4621)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4761)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4629)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4818)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4602)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4655)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4621)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4629)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4602)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7330)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7299)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7260)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7436)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:247)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:165)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
    	at java.lang.reflect.Method.i
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.localise.app, PID: 19402
    java.lang.NoSuchMethodError: No virtual method takePicture(Ljava/io/File;Ljava/util/concurrent/Executor;Landroidx/camera/core/ImageCapture$OnImageSavedCallback;)V in class Landroidx/camera/view/CameraView; or its super classes (declaration of 'androidx.camera.view.CameraView' appears in /data/app/com.localise.app-25mD_WMiY_l9EwY8_Lc1OQ==/base.apk)
        at com.luck.picture.lib.instagram.InstagramCameraView$1.takePictures(InstagramCameraView.java:103)
        at com.luck.picture.lib.instagram.InstagramCaptureLayout.onTouchEvent(InstagramCaptureLayout.java:200)
        at android.view.View.dispatchTouchEvent(View.java:12527)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3026)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2705)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3054)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:444)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1835)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3465)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:402)
        at android.view.View.dispatchPointerEvent(View.java:12768)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5287)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5087)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4602)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4655)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4621)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4761)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4629)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4818)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4602)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4655)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4621)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4629)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4602)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7330)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7299)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7260)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7436)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:247)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:165)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
D/CaptureSession: CameraCaptureSession.onClosed()
I/Process: Sending signal. PID: 19402 SIG: 9

### PR DESCRIPTION
**Pull request by tallot13**
fixed https://github.com/JessYanCoding/InsGallery/issues/15
fixed without access in black layout in cameraview

There is no need to explicitly call CameraX.unbindAll() , since the UseCase is bound to a lifecycle and resources will be automatically freed when the lifecycle reaches the destroyed state. Also, Activity has no onDestroyView method, which is instead owned by Fragments. By the way, for Fragments the proper lifecycle to bind the UseCases to would be the viewLifecycleOwner ‘s lifecycle.

### CODE REVIEW

**Comment by osama-alshanti** [comment]
same issue,, not getting clear solution

**Comment by osama-alshanti** [comment]
After changing camerax_version & camerax_view  like this it's working ..

            camerax_view                  : "1.0.0-alpha10",
            camerax_version               : "1.0.0-beta03",

**Comment by HaXxanParhar** [comment]
After changing the camerax_version & camerax_view to @osama-alshanti mentioned versions, I'm having the following errors: 
output_camerax

The @osama-alshanti mentioned versions take the File but the original library's versions take ImageCapture.OutputFileOptions. As for the library, I cloned it 2 days ago and using it directly in my existing app. I also added the 'ucrop' & 'picture_library' as modules. I'm updating the versions in the module gradle of 'picture_library'.

**Comment by osama-alshanti** [comment]
try @HaXxanParhar use like this mCameraView.takePicture(imageOutFile, ContextCompat.getMainExecutor(getContext()),

**Pull request merged**
